### PR TITLE
bug: TemplateProcessor fix multiline values

### LINKED ISSUE #268: setValue Multi-Line Value
Thank you for the amazing library! This has made my life much easier!

I am using your library to automatically fill out a packing slip. In order to make it easier to maintain and change, I am loading a Word Document as a Template, and then using `setValue()` to update variables. The template I am using has a lot of formatting and I would really prefer to avoid doing it in code if at all possible. It would also make it practically impossible for non-coders to update the template.

The issue I'm having is that I need to insert a multi-line replacement in several places (address, order notes, etc). Are there any plans to implement this in the future? Or am I missing another way to solve this problem, such as XSLT?

I could extend the Template Class with a `setValueForPartMulti()` and if I understand Word's Format correctly, my xml would need to look like the following:

```
 <w:r>
  <w:t>Hello</w:t>
  <w:br/>
  <w:t>world</wt>
</w:r>
```

Could I simply have my custom function `preg_replace('\r\n', '<w:br/>', $value)`? Would any issues arise from doing this?

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/2544656-setvalue-multi-line-value?utm_campaign=plugin&utm_content=tracker%2F323108&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F323108&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gimler**
### Description

Replace line breaks with XML representation to use multi line values with TemplateProcessor.

Fixes #268 #2323 #2486

### Checklist:

- [x] I have run `composer run-script check --timeout=0` and no errors were reported
- [x] The new code is covered by unit tests (check build/coverage for coverage report)
- ~[ ] I have updated the documentation to describe the changes~

### CODE REVIEW

**Comment by gimler** [comment]
@Progi1984 can you take a look please?

File: src/PhpWord/TemplateProcessor.php [hunk 1]
```diff
@@ -1305,6 +1314,18 @@ protected function indexClonedVariables($count, $xmlBlock)
...
     }
 
+    /**
+     * Replace carriage returns with xml.
+     *
+     * @param string $string
+     *
+     * @return string
+     */
+    public function replaceCarriageReturns($string)
```
Comment (Progi1984) [inline src/PhpWord/TemplateProcessor.php:1324]:
```suggestion
    public function replaceCarriageReturns(string $string): string
```

**Review by Progi1984 — COMMENTED** [review]
@gimler Great fix. Could you update the changelog 2.0.0.md, please ?

File: src/PhpWord/TemplateProcessor.php (hunk 1 above)
Comment (gimler) [reply src/PhpWord/TemplateProcessor.php]: fixed

**Comment by gimler** [comment]
@Progi1984 i have updated the changelog.

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @gimler for your contribution.
