### PR TITLE
Hotfix: In headings hyperlinks are ignored. Added w:hyperlink to xpath filter

### LINKED ISSUE #1792: Reading docx with <h?> containing anchors the ancors just get removed.
### Describe the Bug

if you are reading a word document that contains headings with anchors in them getContent() returns the heading with no anchor or anchor text.

### Steps to Reproduce
word document containing: (Sample Docx Attached)
Biographies <- H1
Regular Anchor Aaaa bozz <- p /* Bozz are hyperlinks to http://www.xyz.com */
AAAAA Bozz, Anchor in Heading <-- h2 /* Bozz are hyperlinks to http://www.xyz.com */
On January 31st, 2019, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus hendrerit pellentesque nisl. Vivamus lobortis enim consequat egestas suscipit. In convallis metus id erat eleifend consectetur. Donec tincidunt, dui quis congue sollicitudin, metus arcu mattis erat, sed rutrum eros odio quis ex. Vestibulum sit amet viverra est. Nullam ultrices commodo metus vel iaculis. Fusce nec blandit leo. Curabitur id lacinia libero. Etiam nunc arcu, pharetra sit amet felis non, congue bibendum magna. Duis semper nec metus ac vehicula.

Please provide a code sample that reproduces the issue.

```php
<?php
require_once ('bootstrap.php');

$phpWord = \PhpOffice\PhpWord\IOFactory::load('test.docx');
$htmlWriter = new \PhpOffice\PhpWord\Writer\HTML($phpWord);
$content = $htmlWriter->getContent();

echo $content;
```

### Expected Behavior

<h1>Biographies</h1>
<p style="margin-top: 0; margin-bottom: 0;">Regular Anchor Aaaa <a href="http://www.xyz.com">bozz</a> </p>
<h3>AAAAA , Ancor **<a href="http://www.xyz.com">bozz</a>** in Heading</h3>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-family: 'Arial'; font-size: 12pt;">On January </span><span style="font-family: 'Arial'; font-size: 12pt;">31st</span><span style="font-family: 'Arial'; font-size: 12pt;">, 2019, </span><span style="font-family: 'Arial'; font-size: 12pt;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. </span><span style="font-family: 'Arial'; font-size: 12pt;">Vivamus hendrerit pellentesque nisl. Vivamus lobortis enim consequat egestas suscipit. In convallis metus id erat eleifend consectetur. Donec tincidunt, dui quis congue sollicitudin, metus arcu mattis erat, sed rutrum eros odio quis ex. Vestibulum sit amet viverra est. Nullam ultrices commodo metus vel iaculis. Fusce nec blandit leo. Curabitur id lacinia libero. Etiam nunc arcu, pharetra sit amet felis non, congue bibendum magna. </span><span style="font-family: 'Arial'; font-size: 12pt;">Duis semper nec metus ac vehicula.</span></p>

### Current Behavior

<h1>Biographies</h1>
<p style="margin-top: 0; margin-bottom: 0;">Regular Ancor Aaaa <a href="http://www.xyz.com">bozz</a> </p>
<h3>AAAAA , Ancor in Heading</h3>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-family: 'Arial'; font-size: 12pt;">On January </span><span style="font-family: 'Arial'; font-size: 12pt;">31st</span><span style="font-family: 'Arial'; font-size: 12pt;">, 2019, </span><span style="font-family: 'Arial'; font-size: 12pt;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. </span><span style="font-family: 'Arial'; font-size: 12pt;">Vivamus hendrerit pellentesque nisl. Vivamus lobortis enim consequat egestas suscipit. In convallis metus id erat eleifend consectetur. Donec tincidunt, dui quis congue sollicitudin, metus arcu mattis erat, sed rutrum eros odio quis ex. Vestibulum sit amet viverra est. Nullam ultrices commodo metus vel iaculis. Fusce nec blandit leo. Curabitur id lacinia libero. Etiam nunc arcu, pharetra sit amet felis non, congue bibendum magna. </span><span style="font-family: 'Arial'; font-size: 12pt;">Duis semper nec metus ac vehicula.</span></p>

### Context

Please fill in your environment information:

- PHP 7.1.33
- PHPWord Version: 0.17.0 and tried [dev-develop]
[test.docx](https://github.com/PHPOffice/PHPWord/files/4012777/test.docx)

Thanks for any insight, workaround or nudge in the right direction.

### PR DESCRIPTION
**Pull request by hannesdorn**
### Description

PHPWord is ignoring hyperlinks in headings.
In src\PhpWord\Reader\Word2007\AbstractPart.php only w:r elements are read.

Fixes #1792

### Checklist:

- [x] I have run `composer run-script check --timeout=0` and no errors were reported
- [ ] The new code is covered by unit tests (check build/coverage for coverage report)
- [ ] I have updated the documentation to describe the changes

### CODE REVIEW

File: src/PhpWord/Reader/Word2007/AbstractPart.php [hunk 1]
```diff
@@ -151,7 +151,11 @@ protected function readParagraph(XMLReader $xmlReader, DOMElement $domNode, $par
         } elseif ($headingDepth !== null) {
             // Heading or Title
             $textContent = null;
-            $nodes = $xmlReader->getElements('w:r', $domNode);
+            // 2023-08-02 hannes@dorn.cc
+            // $nodes = $xmlReader->getElements('w:r', $domNode);
+            // delivers only text paragraphs, but no hyperlinks
+            // I extended xpath with w:hyperlink
```
Comment (Progi1984) [inline src/PhpWord/Reader/Word2007/AbstractPart.php:157]:
```suggestion
```

**Review by Progi1984 — COMMENTED** [review]
A small comment

**Review by Progi1984 — APPROVED** [review]
