### PR TITLE
automatic update of the TOC to fix page number missing issues

### LINKED ISSUE #1691: Is there any update for the page numbers missing issue of TOC ?
I use the version 0.16.0,but still has this question.

### PR DESCRIPTION
**Pull request by jgiacomello**
### Description

On several trials, I noticed that despite using `$phpWord->getSettings()->setUpdateFields(true);`, when the generated file was first opened, the chapter index only updated the page numbers and not the list as well, thus losing the references to any paragraphs (H2 and H3) in the document.
On subsequent openings of the file, Word requests the updating of the table of contents fields, but requires the user to specifically select the "update entire table of contents" option, so in the case of a different choice ("update page numbers only") the references to the paragraphs present in each chapter are lost, as mentioned above.

The change made in `PhpWord/Writer/Word2007/Element/TOC.php` on line `116` allows the entire table of contents to be automatically updated by only requiring the generic update of the fields, but without requiring the second step, whatever the number of file openings.

Fixes #1691 #1396 

### Checklist:

- [x] I have run `composer run-script check --timeout=0` and no errors were reported
- [x] The new code is covered by unit tests (check build/coverage for coverage report)
- [x] I have updated the documentation to describe the changes

### CODE REVIEW

**Comment by Progi1984** [comment]
@jgiacomello Hi, Could you update the changelog and add some unit tests, please ?

**Comment by jgiacomello** [comment]
@Progi1984 Hi, thankyou for your feedback!
I updated the changelog and tried to add the tests, but I don't know if they are correct because indeed it seems that the library does not insert page numbers unless they are explicitly indicated when entering a new title, thus leaving the “responsibility” of completion to the actual opening of the file via Word. So I wouldn't know how to really test their correctness, I just know that with that modification they do eventually show up.

Speaking of which, I noticed that with the most updated version of word (2408) the page numbers do show up, but all at 1. They only fix themselves after a _manual_ update of the table of contents.

Thanks

File: tests/PhpWordTests/Writer/Word2007/Element/TOCTest.php [hunk 1]
```diff
@@ -53,4 +53,29 @@ public function testWriteTitlePageNumber(): void
...
+        }
+
+        $doc = TestHelperDOCX::getDocument($phpWord);
+
+        for ($i = 1; $i <= 1; $i++) {
+            self::assertTrue($doc->elementExists('/w:document/w:body/w:p[' . $i . ']/w:hyperlink/w:r[1]/w:t'));
+            self::assertEquals('Title ' . $i, $doc->getElement('/w:document/w:body/w:p[' . $i . ']/w:hyperlink/w:r[1]/w:t')->textContent);
+            self::assertTrue($doc->elementExists('/w:document/w:body/w:p[' . $i . ']/w:hyperlink/w:r[4]/w:instrText'));
+            self::assertEquals('preserve', $doc->getElementAttribute('/w:document/w:body/w:p[' . $i . ']/w:hyperlink/w:r[4]/w:instrText', 'xml:space'));
+        }
```
Comment (Progi1984) [inline tests/PhpWordTests/Writer/Word2007/Element/TOCTest.php:79]:
```suggestion
            self::assertEquals('preserve', $doc->getElementAttribute('/w:document/w:body/w:p[' . $i . ']/w:hyperlink/w:r[4]/w:instrText', 'xml:space'));
            self::assertEquals('PAGEREF  \\h', $doc->getElement('/w:document/w:body/w:p[' . $i . ']/w:hyperlink/w:r[4]/w:instrText')->nodeValue);
        }
```

Comment (Progi1984) [reply tests/PhpWordTests/Writer/Word2007/Element/TOCTest.php:79]: @jgiacomello May be you could adapt the equal value.

**Review by Progi1984 — COMMENTED** [review]
@jgiacomello Could you rebase please the PR ? 

And I have added a last comment.
After that, it will be a merge.

File: docs/changes/1.x/1.4.0.md [hunk 2]
```diff
@@ -28,6 +28,7 @@
 - Reader HTML: Support for inherit value for property line-height by [@Progi1984](https://github.com/Progi1984) fixing [#2683](https://github.com/PHPOffice/PHPWord/issues/2683) in [#2733](https://github.com/PHPOffice/PHPWord/pull/2733)
 - Writer HTML: Fixed null string for Text Elements by [@armagedon007](https://github.com/armagedon007) and [@Progi1984](https://github.com/Progi1984) in [#2738](https://github.com/PHPOffice/PHPWord/pull/2738)
 - Template Processor: Fix 0 considered as empty string by [@cavasinf](https://github.com/cavasinf), [@SnipsMine](https://github.com/SnipsMine) and [@Progi1984](https://github.com/Progi1984) fixing [#2572](https://github.com/PHPOffice/PHPWord/issues/2572), [#2703](https://github.com/PHPOffice/PHPWord/issues/2703) in [#2748](https://github.com/PHPOffice/PHPWord/pull/2748)
+- TOC : Corrected generating TOC to fix page number missing issues [@jgiacomello](https://github.com/jgiacomello) in [#2556](https://github.com/PHPOffice/PHPWord/pull/2556)
```
Comment (Progi1984) [inline docs/changes/1.x/1.4.0.md:31]:
```suggestion
- Word2007 Writer : Corrected generating TOC to fix page number missing issues [@jgiacomello](https://github.com/jgiacomello) in [#2556](https://github.com/PHPOffice/PHPWord/pull/2556)
```

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @jgiacomello for your contribution 🥳
