### PR TITLE
TemplateProcessor cloneBlock wrongly clones images

### LINKED ISSUE #1750: cloneBlock with images inside
I desperately need to clone a block that contains images.

### Steps to Reproduce

In the docx "template":

```
${blC_bloccoTask}
Point

${img_currentTask_brPos:450:450:false}

Point: #${task_id}
Type: ${task_type}
Location: ${task_location}

Photos
${img_currentTask_img1:250:250:false} 
${img_currentTask_img2:250:250:false} 
${img_currentTask_img3:250:250:false} 
${img_currentTask_img4:250:250:false} 
${img_currentTask_img5:250:250:false}

${pageBreak}

${/blC_bloccoTask}
```

In the php code:

```php

$template_processor->cloneBlock('blC_bloccoTask', 0, true, false, $field_content_replacements);

```

where $field_content_replacements is generated in this way:

```
array:2 [▼
  0 => array:14 [▼
    "task_id" => 1
    "task_type" => "corrosion"
    "task_location" => "Starboard"
    "img_currentTask_brPos" => "/private/var/tmp/phpBs1odO.jpg"
    "pageBreak" => "</w:t></w:r><w:r><w:br w:type="page"/></w:r><w:r><w:t>"
    "img_currentTask_img1" => "/private/var/tmp/storage/app/28/photo1.jpg"
    "img_currentTask_img2" => "/private/var/tmp/storage/app/29/photo2.jpg"
    "img_currentTask_img3" => "/private/var/tmp/storage/app/30/photo3.jpg"
    "img_currentTask_img4" => "/private/var/tmp/storage/app/31/photo4.jpg"
    "img_currentTask_img5" => "/private/var/tmp/storage/app/32/photo5.jpg"
  ]
  1 => array:14 [▼
    "task_id" => 2
    "task_type" => "other"
    "task_location" => "Starboard"
    "img_currentTask_brPos" => ""
    "pageBreak" => "</w:t></w:r><w:r><w:br w:type="page"/></w:r><w:r><w:t>"
    "img_currentTask_img1" => "/private/var/tmp/storage/app/33/photo1.jpg"
    "img_currentTask_img2" => "/private/var/tmp/storage/app/34/photo2.jpg"
    "img_currentTask_img3" => "/private/var/tmp/storage/app/35/photo3.jpg"
    "img_currentTask_img4" => "/private/var/tmp/storage/app/36/photo4.jpg"
    "img_currentTask_img5" => "/private/var/tmp/storage/app/37/photo5.jpg"
  ]
]


```

Everything is fine for the "basic" placeholders (the strings, like "task_id", "task_type", "task_location")...but nothing happens when the replacement involves an image.

Any idea?

### Context

- PHP Version: 7.2
- PHPWord Version: "phpoffice/phpword": "v0.17.*"

### PR DESCRIPTION
**Pull request by alarai**
### Description

I was met with the issue reported in #1750 and fixed it. 
The problem was that the regexp to clone and add number did include the size attributes in the tag before the number. So I added a second capture group so that image attributes are properly placed after the tag with it's added number.

I also fixed the call to Process to use an array as it otherwise cause hundred of errors as it now expects an array instead of a string.

All tests are passed and code coverage is unchanged.

Fixes #1750 #1624

### Checklist:

- [X] I have run `composer run-script check --timeout=0` and no errors were reported
- [X] The new code is covered by unit tests (check build/coverage for coverage report)
- [X] I have updated the documentation to describe the changes

### CODE REVIEW

File: src/PhpWord/TemplateProcessor.php [hunk 1]
```diff
@@ -1085,7 +1085,7 @@ protected function indexClonedVariables($count, $xmlBlock)
     {
         $results = array();
         for ($i = 1; $i <= $count; $i++) {
-            $results[] = preg_replace('/\$\{(.*?)\}/', '\${\\1#' . $i . '}', $xmlBlock);
+            $results[] = preg_replace('/\$\{([^:]*?)(:.*?)?\}/', '\${\1#' . $i . '\2}', $xmlBlock);
```
Comment (Amerlander) [inline src/PhpWord/TemplateProcessor.php]: I was just wondering why you're only using one `\` compared to the old regex and to my changes in https://github.com/PHPOffice/PHPWord/pull/1829:

`$results[] = preg_replace('/\$\{(.*?)(:([^}])*)?\}/', '\${\\1#' . $i . '\\2}', $xmlBlock);`

I'm not that much into this regex at the moment, so I don't know how they differ.

btw, this pr will also fix https://github.com/PHPOffice/PHPWord/issues/1624

Comment (troosan) [reply src/PhpWord/TemplateProcessor.php:1088]: @Amerlander that's because in a single quoted string you don't have to double the \
https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.single

Comment (Amerlander) [reply src/PhpWord/TemplateProcessor.php:1088]: Thank you for explanation and for the merge! :)
