### PR TITLE
Generate Table Cell if Row Doesn't Have Any

### LINKED ISSUE #2505: Adding a row to a table without a cell produces a corrupt docx for Word (works in LibreOffice)
### Describe the Bug

Creating a document that includes a table with a row without a cell causes Microsoft Word to consider the document corrupt

### Steps to Reproduce

> 

Please provide a code sample that reproduces the issue.

```php
<?php declare(strict_types=1);

use PhpOffice\PhpWord\SimpleType\TblWidth;

require_once __DIR__ . '/../../vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$table = $section->addTable([
    'width' => 5000,
    'unit' => TblWidth::PERCENT,
]);
$row = $table->addRow();

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save(__DIR__ . '/borked.docx');
```

### Expected Behavior

One of the following would work, the first option being the one that makes the most sense:

 - Row is discarded when writing
   - The current Word2007 Table element write discards tables without rows, so it makes sense to also discard rows without cells while also ensuring that at least one row is written
 - Document is created with an implicit cell added (and required p block element)
   - This would create content in the document not expected 
 - PHP Warning/Notice is raised for the missing cell.
   - No history of the library doing such a thing

### Current Behavior

Document is created and cannot be opened in Word.

When opening and saving in LibreOffice the table is discarded in the saved file

Table row XML created with only the trPr child
```xml
<w:tr>
<w:trPr/>
</w:tr>
```

https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.tablerow?view=openxml-2.8.1 documents this as corrupt

> A tr element has one formatting child element, trPr (§17.4.82), which defines the properties for the row. Each unique property on the table row is specified by a child element of this element. As well, a table row can contain any row-level content, which allows for the use of table cells.
> 
> If a table cell does not include at least one child element other than the row properties, then this document shall be considered corrupt.

### Context

Please fill in your environment information:

- PHP Version: 8.0-8.3
- PHPWord Version: 1.1.0

### PR DESCRIPTION
**Pull request by oleibman**
### Description

Fix #2505. Word treats file as corrupt if a table row does not contain a cell (documentation for why this is so is included in the issue). Person reporting the issue suggests that dropping such a row from the output file is preferred. However, I think generating an empty cell instead is closer to the user's expectation. For example, as demonstrated in the unit tests added with this PR, if a table has row 1 and 3 which contain cells, but row 2 does not, the table as written to the file will have 3 rows, with the second containing an empty cell.

### Checklist:

- [x] I have run `composer run-script check --timeout=0` and no errors were reported
- [x] The new code is covered by unit tests (check build/coverage for coverage report)
- [ ] I have updated the documentation to describe the changes

### CODE REVIEW

**Comment by lucasnetau** [comment]
Hi @oleibman , tested locally and LGTM. Thank you.

File: src/PhpWord/Writer/Word2007/Element/Table.php [hunk 1]
```diff
@@ -103,8 +103,14 @@ private function writeRow(XMLWriter $xmlWriter, RowElement $row): void
...
-            $this->writeCell($xmlWriter, $cell);
+        $cells = $row->getCells();
+        if (count($cells) === 0) {
+            // issue 2505 - Word treats doc as corrupt if row without cell
+            $this->writeCell($xmlWriter, new CellElement());
+        } else {
+            foreach ($cells as $cell) {
+                $this->writeCell($xmlWriter, $cell);
+            }
         }
```
Comment (Progi1984) [inline src/PhpWord/Writer/Word2007/Element/Table.php:114]:
```suggestion
        if (count($row->getCells()) === 0) {
            // Add a cell if the row has no cells (avoid corrupt file)
            $row->addCell();
        }
        foreach ($row->getCells() as $cell) {
            $this->writeCell($xmlWriter, $cell);
        }
```

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php [hunk 2]
```diff
@@ -0,0 +1,218 @@
...
+        $tc->addText('R1C1');
+        $tc = $table->addCell();
+        $tc->addText('R1C2');
+        $row = $table->addRow();
+        /*
+        $tc = $table->addCell();
+        $tc->addText('R2C1');
+        $tc = $table->addCell();
+        $tc->addText('R2C2');
+        */
```
Comment (Progi1984) [inline tests/PhpWordTests/Writer/Word2007/Element/TableTest.php:97]:
```suggestion
        // Add no cell to the current row
```

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php [hunk 3]
```diff
@@ -0,0 +1,218 @@
...
+
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[1]'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[1]/w:tc'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[1]/w:tc[2]'));
+        self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[1]/w:tc[3]'));
+
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[2]'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[2]/w:tc'));
+        self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[2]/w:tc[2]'));
+        //self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[2]/w:tc[3]'));
```
Comment (Progi1984) [inline tests/PhpWordTests/Writer/Word2007/Element/TableTest.php:116]:
```suggestion
```

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php [hunk 4]
```diff
@@ -0,0 +1,218 @@
...
+        $tc = $table->addCell();
+        $tc->addText('R2C1');
+        $tc = $table->addCell();
+        $tc->addText('R2C2');
+        $row = $table->addRow();
+        $tc = $table->addCell();
+        $tc->addText('R3C1');
+        $tc = $table->addCell();
+        $tc->addText('R3C2');
+        */
```
Comment (Progi1984) [inline tests/PhpWordTests/Writer/Word2007/Element/TableTest.php:146]:
```suggestion
        // Add no cell to the current row
```

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php [hunk 5]
```diff
@@ -0,0 +1,218 @@
...
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[2]/w:tc'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[2]/w:tc[2]'));
+        self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[2]/w:tc[3]'));
+
+        self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[3]'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[3]'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[3]/w:tc'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[3]/w:tc[2]'));
+        self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[3]/w:tc[3]'));
+        */
```
Comment (Progi1984) [inline tests/PhpWordTests/Writer/Word2007/Element/TableTest.php:168]:
```suggestion
```

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php [hunk 6]
```diff
@@ -0,0 +1,218 @@
...
+        $section->addText('After table.');
+
+        $doc = TestHelperDOCX::getDocument($phpWord);
+        self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl[2]'), 'only 1 table should be written');
+
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[1]'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[1]/w:tc'));
+        self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[1]/w:tc[2]'));
+        //self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[1]/w:tc[3]'));
```
Comment (Progi1984) [inline tests/PhpWordTests/Writer/Word2007/Element/TableTest.php:155]:
```suggestion
```

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php [hunk 7]
```diff
@@ -0,0 +1,218 @@
...
+        $tc = $table->addCell();
+        $tc->addText('R2C1');
+        $tc = $table->addCell();
+        $tc->addText('R2C2');
+        $row = $table->addRow();
+        $tc = $table->addCell();
+        $tc->addText('R3C1');
+        $tc = $table->addCell();
+        $tc->addText('R3C2');
+        */
```
Comment (Progi1984) [inline tests/PhpWordTests/Writer/Word2007/Element/TableTest.php:193]:
```suggestion
```

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php [hunk 8]
```diff
@@ -0,0 +1,218 @@
...
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[2]/w:tc'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[2]/w:tc[2]'));
+        self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[2]/w:tc[3]'));
+
+        self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[3]'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[3]'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[3]/w:tc'));
+        self::assertTrue($doc->elementExists('/w:document/w:body/w:tbl/w:tr[3]/w:tc[2]'));
+        self::assertFalse($doc->elementExists('/w:document/w:body/w:tbl/w:tr[3]/w:tc[3]'));
+        */
```
Comment (Progi1984) [inline tests/PhpWordTests/Writer/Word2007/Element/TableTest.php:216]:
```suggestion
```

**Review by Progi1984 — COMMENTED** [review]
@oleibman Great job. 

Added some comments.
Could you update the changelog file, too, please ?

File: src/PhpWord/Writer/Word2007/Element/Table.php (hunk 1 above)
Comment (oleibman) [reply src/PhpWord/Writer/Word2007/Element/Table.php:114]: I'm not sure about this suggestion. The way I have coded it, there is no change to the user's document object after the write. With your suggestion, there will be a new cell added to the user's document object. This seems unexpected. If the user were to write, then add a cell to the row (perhaps user is preparing multiple documents), it would now be in the row's second cell rather than the first. Given that, do you still think this should be recoded?

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php (hunk 2 above)
Comment (oleibman) [reply tests/PhpWordTests/Writer/Word2007/Element/TableTest.php]: Done. Tests were basically cloned from each other. It was helpful during development to just comment out what differed from test to test. Agree that's not needed now.

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php (hunk 4 above)
Comment (oleibman) [reply tests/PhpWordTests/Writer/Word2007/Element/TableTest.php]: Done.

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php (hunk 6 above)
Comment (oleibman) [reply tests/PhpWordTests/Writer/Word2007/Element/TableTest.php]: Done.

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php (hunk 3 above)
Comment (oleibman) [reply tests/PhpWordTests/Writer/Word2007/Element/TableTest.php]: Done.

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php (hunk 5 above)
Comment (oleibman) [reply tests/PhpWordTests/Writer/Word2007/Element/TableTest.php]: Done.

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php (hunk 7 above)
Comment (oleibman) [reply tests/PhpWordTests/Writer/Word2007/Element/TableTest.php]: Done.

File: tests/PhpWordTests/Writer/Word2007/Element/TableTest.php (hunk 8 above)
Comment (oleibman) [reply tests/PhpWordTests/Writer/Word2007/Element/TableTest.php]: Done.

**Comment by oleibman** [comment]
@Progi1984 Change log updated, all your suggestions except one are incorporated; that one needs further discussion,

File: src/PhpWord/Writer/Word2007/Element/Table.php (hunk 1 above)
Comment (lucasnetau) [reply src/PhpWord/Writer/Word2007/Element/Table.php:114]: This would mutate the document object when writing out a file. As a user I would expect that the document object is not modified.

**Review by Progi1984 — APPROVED** [review]
